test before commit

diff --git a/scripts/hooks/pre-commit b/scripts/hooks/pre-commit
--- a/scripts/hooks/pre-commit
+++ b/scripts/hooks/pre-commit
@@ -1,5 +1,15 @@
 #!/bin/sh
 
+echo "Testing..."
+go test ./...
+
+if [ $? -eq 0 ]; then
+	echo "Test successd"
+else
+	echo "Test failed"
+	exit 1
+fi
+
 echo "Building..."
 go build -o bin/dev .
 
